
try{
    hello();
}catch(err){
    console.log(err)
}